// GENERATED by tools/export-web.py from index.html — do not edit.
// Re-run the generator after tuning in the lab.

/** Param key -> GLSL uniform. `null` means the host consumes it, not the shader. */
export const UNIFORM_MAP = {
  speed: null,
  scale: "uScale",
  angle: "uAngle",
  drift: "uDrift",
  warp: "uWarp",
  flow: "uFlow",
  detail: "uDetail",
  rough: "uRough",
  soft: "uSoft",
  blur: "uBlur",
  norm: "uNorm",
  p1: "uP1",
  p2: "uP2",
  p3: "uP3",
  bump: "uBump",
  lightAngle: "uLightAngle",
  lightElev: "uLightElev",
  ambient: "uAmbient",
  spec: "uSpec",
  specPow: "uSpecPow",
  fresnel: "uFresnel",
  contrast: "uContrast",
  bright: "uBright",
  gamma: "uGamma",
  lift: "uLift",
  bloom: "uBloom",
  vignette: "uVignette",
  invert: "uInvert",
  auto: null,
  target: null,
  grain: "uGrain",
  grainScale: "uGrainScale",
  stipple: "uStipple",
  grain2: "uGrain2",
  bands: "uBands",
  p4: "uP4",
  renderScale: null,
};

export const BASE = {
    speed:1, scale:1, angle:0, drift:1, warp:.9, flow:.9,
    detail:5, rough:.5, soft:.10, blur:0, norm:.75, p1:.5, p2:.2, p3:.3, p4:.5,
    bump:1, lightAngle:-2.2, lightElev:.45, ambient:.35, spec:.5, specPow:5, fresnel:.1,
    contrast:1.15, bright:0, gamma:1, lift:.01, bloom:.25, vignette:.35, invert:0,
    auto:.8, target:.24,
    grain:.045, grainScale:1.4, grainAnim:1, bands:0, stipple:0, grain2:0,
    renderScale:1,
  };

export const PRESETS = [
    { id:0, name:"Silk", note:"soft flowing folds",
      labels:{p1:"Fold stretch", p2:"Crease", p3:"—", p4:"—"},
      v:{ speed:.45, scale:.72, angle:-.38, drift:1.0, warp:1.15,
          detail:2.8, rough:.55, soft:.20, blur:.34, norm:.8, p1:.70, p2:.10, p3:0,
          bump:.80, lightAngle:-2.45, lightElev:.55, ambient:.18, spec:.42, specPow:3.8, fresnel:.10,
          contrast:1.45, bright:-.05, gamma:1.30, lift:.012, bloom:.42, vignette:.55, target:.22,
          grain:.055, grainScale:1.3, bands:0 } },

    { id:1, name:"Brushed Metal", note:"anisotropic sheen",
      labels:{p1:"Streak stretch", p2:"Band freq", p3:"Band mix", p4:"—"},
      v:{ speed:.6, scale:1.0, angle:-.06, drift:.5, warp:.25,
          detail:3.2, rough:.45, soft:.32, blur:.38, norm:.5, p1:.58, p2:.16, p3:.18,
          bump:.55, lightAngle:-1.95, lightElev:.40, ambient:.30, spec:.60, specPow:5.4, fresnel:.16,
          contrast:1.06, bright:-.01, gamma:1.05, lift:.02, bloom:.35, vignette:.44, target:.26,
          grain:.042, grainScale:1.2, bands:.05 } },

    { id:2, name:"Sand", note:"dunes + wind ripple",
      labels:{p1:"Dune squash", p2:"Ripple freq", p3:"Ripple mix", p4:"—"},
      v:{ speed:.35, scale:.72, angle:.22, drift:.8, warp:.75,
          detail:3.6, rough:.48, soft:.20, blur:.20, norm:.45, p1:.46, p2:.16, p3:.18,
          bump:.90, lightAngle:-2.95, lightElev:.24, ambient:.26, spec:.28, specPow:3.6, fresnel:.06,
          contrast:1.12, bright:0, gamma:1.12, lift:.02, bloom:.16, vignette:.42, target:.25,
          grain:.10, grainScale:.9, bands:0 } },

    { id:3, name:"Dust", note:"drifting motes + haze",
      labels:{p1:"Haze falloff", p2:"Mote density", p3:"Light shaft", p4:"—"},
      v:{ speed:.5, scale:.85, angle:0, drift:1.3, warp:.5,
          detail:3.8, rough:.48, soft:.34, blur:.42, norm:.7, p1:.50, p2:.16, p3:.50,
          bump:.35, lightAngle:-2.1, lightElev:.75, ambient:.40, spec:.22, specPow:5.2, fresnel:.08,
          contrast:1.22, bright:-.02, gamma:1.35, lift:.012, bloom:.55, vignette:.58, target:.19,
          grain:.075, grainScale:1.6, bands:0 } },

    { id:4, name:"Ink Smoke", note:"billowing wisps",
      labels:{p1:"Density", p2:"Wisp", p3:"—", p4:"—"},
      v:{ speed:.42, scale:.90, angle:.1, drift:1.0, warp:1.20,
          detail:4.4, rough:.52, soft:.30, blur:.34, norm:.7, p1:.52, p2:.22, p3:0,
          bump:.45, lightAngle:-2.35, lightElev:.55, ambient:.40, spec:.25, specPow:4.2, fresnel:.08,
          contrast:1.18, bright:.01, gamma:1.20, lift:.014, bloom:.40, vignette:.46, target:.21,
          grain:.06, grainScale:1.3, bands:0 } },

    { id:5, name:"Liquid Chrome", note:"reflective flow",
      labels:{p1:"Sheen freq", p2:"Hardness", p3:"—", p4:"—"},
      v:{ speed:.55, scale:.95, angle:0, drift:1.0, warp:1.0,
          detail:3.0, rough:.5, soft:.10, blur:.14, norm:.8, p1:.52, p2:.22, p3:0,
          bump:1.30, lightAngle:-2.0, lightElev:.38, ambient:.32, spec:.75, specPow:5.6, fresnel:.24,
          contrast:1.10, bright:-.02, gamma:1.00, lift:.04, bloom:.40, vignette:.38, target:.23,
          grain:.045, grainScale:1.2, bands:.04 } },

    // ---- grain-forward set: flat tonal lobes, heavy stipple, fluid advection ----
    { id:6, name:"Grain Field", note:"flat lobes, heavy stipple",
      labels:{p1:"Edge falloff", p2:"Lobe bias", p3:"—", p4:"—"},
      v:{ speed:.42, scale:1.0, angle:-.2, drift:.6, warp:.4, flow:1.15,
          detail:2.4, rough:.52, soft:.30, blur:.22, norm:.55, p1:.62, p2:.45, p3:0,
          bump:.08, lightAngle:-2.2, lightElev:.9, ambient:.92, spec:0, specPow:4, fresnel:0,
          contrast:1.14, bright:-.01, gamma:1.16, lift:.004, bloom:.10, vignette:.34, target:.25,
          grain:.62, grainScale:1.0, stipple:1.0, grain2:.18, bands:0 } },

    { id:7, name:"Chrome Grain", note:"chrome sheen, stippled",
      labels:{p1:"Sheen freq", p2:"Hardness", p3:"—", p4:"—"},
      v:{ speed:.55, scale:.95, angle:0, drift:1.0, warp:1.0, flow:.85,
          detail:3.0, rough:.5, soft:.12, blur:.14, norm:.8, p1:.52, p2:.24, p3:0,
          bump:1.10, lightAngle:-2.0, lightElev:.38, ambient:.34, spec:.70, specPow:5.4, fresnel:.22,
          contrast:1.08, bright:-.01, gamma:1.00, lift:.03, bloom:.38, vignette:.36, target:.25,
          grain:.44, grainScale:1.1, stipple:.72, grain2:.10, bands:.03 } },

    { id:8, name:"Vapor", note:"maximum fluidity",
      labels:{p1:"Density", p2:"Wisp", p3:"—", p4:"—"},
      v:{ speed:.50, scale:.90, angle:.12, drift:1.0, warp:.8, flow:1.45,
          detail:3.4, rough:.52, soft:.32, blur:.36, norm:.65, p1:.48, p2:.16, p3:0,
          bump:.24, lightAngle:-2.35, lightElev:.70, ambient:.70, spec:.12, specPow:4.0, fresnel:.06,
          contrast:1.12, bright:0, gamma:1.18, lift:.010, bloom:.26, vignette:.42, target:.24,
          grain:.34, grainScale:1.3, stipple:.55, grain2:.06, bands:0 } },
  ];

/** Full param set for a preset: BASE overlaid with the preset's overrides. */
export function paramsFor(preset) {
  const p =
    typeof preset === "number"
      ? PRESETS[preset]
      : PRESETS.find((x) => x.name.toLowerCase() === String(preset).toLowerCase());
  if (!p) {
    throw new Error(
      `Unknown preset "${preset}". Available: ${PRESETS.map((x) => x.name).join(", ")}`,
    );
  }
  return { ...BASE, ...p.v };
}
