// GENERATED by tools/export-web.py from index.html — do not edit.
// Re-run the generator after tuning in the lab.

export const VERT = /* glsl */ `
attribute vec2 aPos;
void main(){ gl_Position = vec4(aPos,0.0,1.0); }
`;

export const FRAG = /* glsl */ `
precision highp float;

uniform vec2  uRes;
uniform float uTime;
uniform float uSeed;
uniform int   uPreset;

// motion / form
uniform float uScale, uAngle, uWarp, uDrift, uDetail, uRough, uBump, uSoft, uBlur, uNorm;
uniform float uP1, uP2, uP3, uP4;
// light
uniform float uLightAngle, uLightElev, uAmbient, uSpec, uSpecPow, uFresnel;
// grade
uniform float uContrast, uBright, uGamma, uInvert, uBloom, uVignette, uLift, uGain;
// texture
uniform float uGrain, uGrainScale, uGrainAnim, uBands, uStipple, uGrain2, uGrainSeed;
uniform float uFlow;

#define PI 3.14159265359

mat2 rm(float a){ float c=cos(a), s=sin(a); return mat2(c,-s,s,c); }

// Dave Hoskins' hash12. The fract(dot()) trick banded, and the iq
// fract(p*k)->p.x*p.y form collapses to 0 along whole lattice lines, which showed
// up as a hairline straight streak across the dunes. This one has neither failure.
float hash21(vec2 p){
  vec3 p3 = fract(vec3(p.xyx) * 0.1031);
  p3 += dot(p3, p3.yzx + 33.33);
  return fract((p3.x + p3.y) * p3.z);
}
float vnoise(vec2 p){
  vec2 i = floor(p), f = fract(p);
  vec2 u = f*f*f*(f*(f*6.0-15.0)+10.0);   // quintic: C2 continuous, no creases
  float a = hash21(i), b = hash21(i+vec2(1,0));
  float c = hash21(i+vec2(0,1)), d = hash21(i+vec2(1,1));
  return mix(mix(a,b,u.x), mix(c,d,u.x), u.y);
}
// Fixed 2/3-octave fbm. GLSL ES 1.00 wants constant loop bounds, so the general
// fbm below always spins its full loop — using it for the warp and level-lock
// lookups burned ~6 wasted noise evals each. These are the hot path.
float fbm2(vec2 p){
  float s = 0.5*vnoise(p);
  p = rm(0.5)*p*2.0;
  s += 0.25*vnoise(p);
  return s/0.75;
}
float fbm3(vec2 p){
  float s = 0.5*vnoise(p);
  p = rm(0.5)*p*2.0;  s += 0.25*vnoise(p);
  p = rm(0.5)*p*2.0;  s += 0.125*vnoise(p);
  return s/0.875;
}

// continuous-octave fbm (uDetail can be fractional; no dynamic loop bounds)
float fbm(vec2 p, float oct, float gain, float lac){
  float s=0.0, a=0.5, n=0.0;
  for(int i=0;i<6;i++){
    float w = clamp(oct - float(i), 0.0, 1.0);
    s += a*w*vnoise(p);
    n += a*w;
    p = rm(0.5)*p*lac;
    a *= gain;
  }
  return s/max(n,1e-4);
}
float rfbm(vec2 p, float oct, float gain){
  float s=0.0, a=0.5, n=0.0;
  for(int i=0;i<6;i++){
    float w = clamp(oct - float(i), 0.0, 1.0);
    float v = vnoise(p);
    v = 1.0 - abs(2.0*v - 1.0);
    v *= v;
    s += a*w*v;
    n += a*w;
    p = rm(0.7)*p*2.05;
    a *= gain;
  }
  return s/max(n,1e-4);
}
// The fold aesthetic needs very low spatial frequency, which means the whole
// frame can sit inside one noise lobe and drift bright/dark as it animates.
// Subtracting the slow level at the same (warped) coordinate cancels that drift
// while leaving the big soft shapes intact.
float levelLock(float h, vec2 p){
  if(uNorm < 0.001) return h;
  float lvl = fbm2(p*0.30);
  return clamp(h - (lvl - 0.5)*uNorm, 0.0, 1.0);
}

// Iterated noise advection. True curl-noise would need 4 fbm calls per step
// (~36 noise evals per field sample, far too slow here); pushing the point
// through successive rotated noise offsets reads just as fluid for a fraction
// of the cost, because each pass folds the previous pass's distortion.
vec2 advect(vec2 p, float t, float amt, int steps){
  for(int i=0;i<3;i++){
    if(i >= steps) break;
    float fi = float(i);
    vec2 w = vec2(
      fbm2(p*(0.8 + fi*0.30) + vec2(t*(0.09 + fi*0.03), 2.1*fi)),
      fbm2(p*(0.8 + fi*0.30) + vec2(3.3*fi, -t*(0.08 + fi*0.025)))
    );
    p += (w - 0.5) * amt * (2.4/(1.0 + fi));
    p = rm(0.5)*p;
  }
  return p;
}

float motes(vec2 p, float t){
  float sum = 0.0;
  for(int i=0;i<3;i++){
    float fi = float(i);
    vec2 g = p*(3.0 + fi*4.5) + vec2(t*(0.10+fi*0.05), -t*(0.06+fi*0.04));
    vec2 id = floor(g), f = fract(g)-0.5;
    float r = hash21(id + fi*13.7 + uSeed);
    vec2 off = (vec2(hash21(id+7.1), hash21(id+3.3)) - 0.5)*0.72;
    float d = length(f-off);
    sum += smoothstep(0.11, 0.0, d) * step(0.84, r) * (0.4 + 0.6*hash21(id+1.7));
  }
  return sum;
}

// ---------------- height field per preset ----------------
float field(vec2 q){
  float t = uTime;
  float S = uSeed*17.31;
  q = rm(uAngle)*q*uScale;
  q += S;

  // 0 — SILK  (reference: soft flowing folds)
  if(uPreset==0){
    vec2 p = q*vec2(1.0, mix(1.0, 0.30, uP1));
    vec2 w = vec2(
      fbm3(p*0.60 + vec2( t*0.07, -t*0.030)),
      fbm3(p*0.60 + vec2(4.7,2.3) + vec2(-t*0.05, t*0.055))
    );
    p += (w-0.5)*uWarp*3.2;
    vec2 bp = p*1.15 + vec2(0.0, t*uDrift*0.25);
    float h = levelLock(fbm(bp, uDetail, uRough, 2.0), bp);
    h = smoothstep(0.14, 0.86, h);
    h = mix(h, 1.0-abs(1.0-2.0*h), uP2);          // creases
    return h;
  }

  // 1 — BRUSHED METAL  (streaks run across the frame, not down it)
  if(uPreset==1){
    vec2 p = q*vec2(mix(0.30, 0.045, uP1), mix(1.0, 5.5, uP1));
    p += vec2(t*uDrift*0.22, t*0.015);
    float h = levelLock(fbm(p, uDetail, uRough, 2.2), p);
    float band = 0.5 + 0.5*sin(h*6.2831*mix(1.0, 6.0, uP2) + t*0.4);
    return mix(h, band, uP3);
  }

  // 2 — SAND
  if(uPreset==2){
    vec2 p = q*0.52;
    vec2 w = vec2(fbm2(p*0.45 + t*0.020),
                  fbm2(p*0.45 + 3.3 - t*0.018));
    p += (w-0.5)*uWarp*2.4;
    vec2 dp = p*vec2(1.0, mix(1.0, 2.6, uP1)) + vec2(t*uDrift*0.18, 0.0);
    float dunes = levelLock(rfbm(dp, uDetail, uRough), dp);
    float rip = 0.5 + 0.5*sin(p.y*mix(10.0, 55.0, uP2) + fbm3(p*2.0)*9.0 - t*uDrift*0.5);
    return clamp(dunes + rip*uP3*0.16, 0.0, 1.0);
  }

  // 3 — DUST  (haze + light shaft only; motes are emissive, see glow())
  if(uPreset==3){
    vec2 p = q*0.62;
    vec2 hp = p + vec2(t*uDrift*0.09, -t*uDrift*0.05);
    float haze = levelLock(fbm(hp, uDetail, uRough, 2.0), hp);
    haze = pow(clamp(haze,0.0,1.0), mix(0.55, 2.6, uP1));
    float shaft = 0.5 + 0.5*sin(dot(p, vec2(0.75,-0.66))*0.75 + t*uDrift*0.06);
    shaft = smoothstep(0.15, 1.0, shaft);
    return clamp(mix(haze, haze*0.55 + shaft*0.55, uP3), 0.0, 1.0);
  }

  // 4 — INK SMOKE
  if(uPreset==4){
    vec2 p = q*0.85;
    for(int i=0;i<2;i++){
      float fi = float(i);
      vec2 w = vec2(
        fbm3(p*0.8 + vec2(t*0.05*(1.0+fi), 1.7*fi)),
        fbm3(p*0.8 + vec2(2.9*fi, -t*0.045*(1.0+fi)))
      );
      p += (w-0.5)*uWarp*2.2;
    }
    vec2 sp = p + vec2(0.0, -t*uDrift*0.18);
    float h = levelLock(fbm(sp, uDetail, uRough, 2.1), sp);
    h = pow(clamp(h,0.0,1.0), mix(0.6, 1.9, uP1));
    h = mix(h, abs(2.0*h-1.0), uP2);              // wisps
    return h;
  }

  // 5 — LIQUID CHROME  (directional sheen bands, not concentric rings)
  if(uPreset==5){
    vec2 p = q*1.05;
    float tt = t*0.45;
    for(int i=0;i<5;i++){
      p = rm(0.62)*p;
      p += 0.42*vec2(sin(p.y*1.6 + tt), cos(p.x*1.6 - tt))*uWarp;
    }
    float h = 0.5 + 0.5*sin(dot(p, vec2(0.82,0.57))*mix(1.2, 9.0, uP1)
                            - tt*1.6 + fbm(p*0.5, uDetail, uRough, 2.0)*7.0);
    return mix(h, h*h*(3.0-2.0*h), uP2);
  }

  // 6 — GRAIN FIELD  (flat tonal lobes; all the character comes from stipple)
  if(uPreset==6){
    vec2 p = advect(q*0.55, t, uFlow, 2);
    float h = levelLock(fbm(p, uDetail, uRough, 2.0), p);
    h = smoothstep(mix(0.5, 0.02, uP1), mix(0.5, 0.98, uP1), h);
    return pow(clamp(h, 0.0, 1.0), mix(0.5, 2.5, uP2));
  }

  // 7 — CHROME GRAIN  (the Liquid Chrome sheen, advected and stippled)
  if(uPreset==7){
    vec2 p = q*1.0;
    float tt = t*0.40;
    for(int i=0;i<3;i++){
      p = rm(0.62)*p;
      p += 0.42*vec2(sin(p.y*1.6 + tt), cos(p.x*1.6 - tt))*uWarp;
    }
    p = advect(p, t, uFlow*0.7, 2);
    float h = 0.5 + 0.5*sin(dot(p, vec2(0.82,0.57))*mix(1.2, 9.0, uP1)
                            - tt*1.6 + fbm(p*0.5, uDetail, uRough, 2.0)*7.0);
    return mix(h, h*h*(3.0-2.0*h), uP2);
  }

  // 8 — VAPOR  (maximum fluidity: three advection passes)
  vec2 p = advect(q*0.80, t, uFlow, 3);
  float h = levelLock(fbm(p, uDetail, uRough, 2.0), p);
  h = mix(h, abs(2.0*h - 1.0), uP2);
  return pow(clamp(h, 0.0, 1.0), mix(0.6, 2.2, uP1));
}

// emissive layer — added after shading so it never gets embossed into 3D beads
float glow(vec2 q){
  if(uPreset==3){
    vec2 p = rm(uAngle)*q*uScale + uSeed*17.31;
    return motes(p*0.85, uTime*max(uDrift,0.02)) * uP2;
  }
  return 0.0;
}

void main(){
  vec2 uv = (gl_FragCoord.xy - 0.5*uRes) / uRes.y;

  float e = mix(0.0012, 0.030, uSoft);
  float h  = field(uv);
  float hx = field(uv + vec2(e,0.0)) - field(uv - vec2(e,0.0));
  float hy = field(uv + vec2(0.0,e)) - field(uv - vec2(0.0,e));

  // soft focus: 4 diagonal taps averaged into the base tone (normals stay crisp)
  if(uBlur > 0.001){
    float r = uBlur*0.05;
    float b = field(uv+vec2( r, r)) + field(uv+vec2(-r, r))
            + field(uv+vec2( r,-r)) + field(uv+vec2(-r,-r));
    h = mix(h, (h + b)*0.2, 0.85);
  }

  vec3 N = normalize(vec3(-hx*uBump/ (e*8.0), -hy*uBump/(e*8.0), 1.0));
  vec3 L = normalize(vec3(cos(uLightAngle), sin(uLightAngle), mix(0.15, 1.6, uLightElev)));
  vec3 V = vec3(0.0,0.0,1.0);
  vec3 H = normalize(L+V);

  float diff = max(dot(N,L), 0.0);
  float spec = pow(max(dot(N,H), 0.0), exp2(uSpecPow)) * uSpec;
  float fres = pow(1.0 - max(dot(N,V),0.0), 3.0) * uFresnel;

  float lum = h * (uAmbient + (1.0-uAmbient)*diff) + spec + fres;
  lum += glow(uv);
  lum *= uGain;                                          // auto-exposure servo (see JS)

  // optional contour banding (topographic / sheen rings)
  if(uBands > 0.001){
    float b = 0.5 + 0.5*sin(h*6.2831*8.0);
    lum = mix(lum, lum*0.55 + b*0.55, uBands);
  }

  lum += uBloom * pow(clamp(lum,0.0,1.0), 3.0) * 1.4;   // cheap glow on peaks
  lum = (lum - 0.5)*uContrast + 0.5 + uBright;
  lum = mix(lum, 1.0-lum, uInvert);
  lum = pow(clamp(lum, 0.0, 1.0), uGamma);
  lum = uLift + lum*(1.0 - uLift);                       // black lift

  // vignette
  vec2 vq = (gl_FragCoord.xy/uRes - 0.5) * vec2(uRes.x/uRes.y, 1.0);
  float vig = 1.0 - uVignette*smoothstep(0.20, 0.95, length(vq)*1.25);
  lum *= vig;

  // ---- grain (resolution-independent size) ----
  vec2 gp = gl_FragCoord.xy * (1080.0/uRes.y) / max(uGrainScale, 0.25);
  float tg = uGrainAnim*uGrainSeed;   // host drives the cadence: 24/s live, 1/frame in video
  float fine   = hash21(gp + tg*7.13);
  float coarse = hash21(floor(gp*0.34) + tg*3.71);
  float gn = mix(fine, coarse, clamp(uGrain2, 0.0, 1.0)) - 0.5;

  // Flat grain noises the whole frame evenly. Weighting by lum*(1-lum) instead
  // puts every bit of it in the transitions and leaves the blacks and the whites
  // clean — that is what makes the reference stipple read as stipple.
  float wgt = mix(1.0, 4.0*lum*(1.0 - lum), uStipple);
  lum += gn * uGrain * wgt;

  lum = clamp(lum, 0.0, 1.0);
  gl_FragColor = vec4(vec3(lum), 1.0);
}
`;
